# fpsを動画に合わせる
correct-pts=yes

# スクショの設定
screenshot-format=png

# On Screen Display Settings
osd-bar=no
osd-font-size=30
osd-duration=3000
osd-font="DroidSansMono Nerd Font"
osd-border-size=1
osd-scale-by-window=no

# 字幕は非表示
sub-visibility=no

# Volume Settings
#softvol=yes
volume-max=200
volume=15
